version: "3"

services:
  app:
    build:
      context: ""

    ports:
      - "8000:8000"
      
    restart: always

    command: >
      sh -c "
        python database/app.py &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
      
    depends_on:
      - postgresdb
      
    networks:
      - monreseau    
    links:
      - postgresdb
 
  test-app:
    build:
      context: "."
      args:
        - ENVIRONMENT=test
    depends_on:
      - postgresdb
    volumes:
      - .:/app
    links:
      - postgresdb
    networks:
      - monreseau 
    restart: "no"

    
  postgresdb:

    image: postgres:14.1-alpine

    networks:
      - monreseau    

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  admine:

    image: adminer
    restart: always
    depends_on:
      - postgresdb
    ports:
      - 8080:8080
    networks:
      - monreseau    
    links:
      - postgresdb

networks:
  monreseau:
     name: monreseau